### ISSUE TITLE
[Bug] rpx2vw makes repeating-linear-gradient miss transparent value

### ISSUE THREAD

**Issue by SoloJiang** [raxjs/rax-app#763]
style-unit handles wrong with `background-image: repeating-linear-gradient(-50deg, transparent 0 10rpx, #FE5600 10rpx 18rpx )`, it should transform to `transparent 0 1.333vw`

![image](https://user-images.githubusercontent.com/14757289/123751044-dbb53e80-d8e9-11eb-9468-1a6e1d780106.png)

#### Source

![image](https://user-images.githubusercontent.com/14757289/123751072-e5d73d00-d8e9-11eb-94e0-47ae3caf70d0.png)

**Comment by wjq990112** [comment]
This problem is caused by `cssnano` used by `OptimizeCSSAssetsPlugin`, still exist and do not know the fix time.

It is a rare and complicated scene, you can use a hack way to avoid.

Issue: [https://github.com/cssnano/cssnano/issues/650](https://github.com/cssnano/cssnano/issues/650)

```css
.foo {
  background-image: repeating-linear-gradient(-50deg, transparent 0.0001rpx 10rpx, #FE5600 10rpx 18rpx);
}
```
